{% set name = "ics" %}
{% set version = "0.7.3" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/ics-py/ics.py/archive/v{{ version }}.tar.gz
  sha256: e7355379f15c7cbdbfd8be322deaf192c5064aab9a19c9c0b7a198b90afc21aa

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation

requirements:
  host:
    - python {{ python_min }}
    - setuptools <72  # setup.py imports setuptools.command.test
    - pip
    # setup.py imports the package
    - python-dateutil
    - arrow >=0.11
    - six >1.5
    - tatsu >4.2,<5.16.0
    - attrs >=19.1.0
  run:
    - python >={{ python_min }}
    - python-dateutil
    - arrow >=0.11
    - six >1.5
    - tatsu >4.2,<5.16.0
    - attrs >=19.1.0

test:
  imports:
    - ics
  requires:
    - python {{ python_min }}
    - pip

about:
  home: https://github.com/ics-py/ics-py/
  license: Apache-2.0
  license_file: LICENSE.rst
  summary: "Pythonic iCalendar (RFC 5545) Parser"
  doc_url: https://icspy.readthedocs.io/en/stable/
  dev_url: https://github.com/C4ptainCrunch/ics.py/

extra:
  recipe-maintainers:
    - ickc
