{% set name = "ics" %}
{% set version = "0.7.2" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/ics-py/ics.py/archive/v{{ version }}.tar.gz
  sha256: ea66b91463013ef36ce34c502491d2161a899e57111dcc4fd1dca6730a2f9ddf

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python>=3.7
  run:
    - arrow >=0.11
    - attrs >=19.1.0
    - python>=3.7
    - python-dateutil
    - six >1.5
    - tatsu >4.2

test:
  imports:
    - ics

about:
  home: https://github.com/ics-py/ics-py/
  license: Apache-2.0
  license_file: LICENSE.rst
  summary: Pythonic iCalendar (RFC 5545) Parser
  doc_url: https://icspy.readthedocs.io/en/stable/
  dev_url: https://github.com/C4ptainCrunch/ics.py/

extra:
  recipe-maintainers:
    - ickc
